In [13]:
# 검증세트
import pandas as pd
wine = pd.read_csv('https://bit.ly/wine_csv_data')

In [14]:
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

In [15]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2,
                                                                     random_state=42)

In [16]:
sub_input, val_input, sub_target, val_target = train_test_split(
train_input, train_target, test_size=0.2, random_state=42)

In [17]:
print(sub_input.shape, val_input.shape)

(4157, 3) (1040, 3)


In [18]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(sub_input, sub_target)
print(dt.scores(sub_input, sub_target))
print(dt.scores(val_input, val_target))

AttributeError: 'DecisionTreeClassifier' object has no attribute 'scores'

In [19]:
# 교차검증
from sklearn.model_selection import cross_validate
scores = cross_validate(dt, train_input, train_target)
print(scores)

{'fit_time': array([0.00698137, 0.0050621 , 0.00499582, 0.0049808 , 0.00498533]), 'score_time': array([0.00099754, 0.00101256, 0.00099468, 0.0009973 , 0.00099707]), 'test_score': array([0.86923077, 0.84807692, 0.88065448, 0.85563041, 0.84215592])}


In [20]:
import numpy as np
print(np.mean(scores['test_score']))

0.859149700155475


In [21]:
from sklearn.model_selection import StratifiedGroupKFold
scores = cross_validate(dt, train_input, train_target, cv=StratifiedGroupKFold())
print(np.mean(scores['test_score']))

nan


C:\Users\admin\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 418, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py", line 651, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 467, in predict
    X = self._validate_X_predict(X, check_input)
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 433, in _validate_X_predict
    X = self._validat

In [22]:
splitter = StratifiedGroupKFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_validate(dt, train_input, train_target, cv=splitter)
print(np.mean(scores['test_score']))

nan


C:\Users\admin\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 418, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py", line 651, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 467, in predict
    X = self._validate_X_predict(X, check_input)
  File "C:\Users\admin\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 433, in _validate_X_predict
    X = self._validat

In [23]:
# 하이퍼 파리미터 튜닝
from sklearn.model_selection import GridSearchCV
params = {'min_impurity_decrease':[0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}

In [26]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params,n_jobs=-1)

In [27]:
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [28]:
print(gs.best_params_)

{'min_impurity_decrease': 0.0001}


In [30]:
print(gs.cv_results_['mean_test_score'])

[0.86819297 0.86453617 0.86492226 0.86780891 0.86761605]


In [31]:
best_index = np.argmax(gs.cv_results_['mean_test_score'])
print(gs.cv_results_['params'][best_index])

{'min_impurity_decrease': 0.0001}


In [34]:
params = {'min_imqurity_dectease':np.arange(0.0001, 0.001, 0.0001),
         'max_depth' : range(5,20,1),
         'min_samples_split' : range(2, 100, 10)}

In [35]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)

ValueError: Invalid parameter min_imqurity_dectease for estimator DecisionTreeClassifier(max_depth=5, random_state=42). Check the list of available parameters with `estimator.get_params().keys()`.

In [36]:
print(gs.best_params)

AttributeError: 'GridSearchCV' object has no attribute 'best_params'

In [37]:
from scipy.stats import uniform, randint
rgn = randint(0, 10)
rgn.rvs(10)

array([5, 6, 6, 7, 1, 8, 1, 4, 8, 3])

In [41]:
np.unique(rgn.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([106,  86,  94,  91, 107,  94, 116,  95, 103, 108], dtype=int64))

In [42]:
ugen = uniform(0, 1)
ugen.rvs(10)

array([0.83488712, 0.30974066, 0.10404496, 0.58117674, 0.05144023,
       0.54381678, 0.82635968, 0.28505262, 0.34550661, 0.6422898 ])

In [43]:
params = {'min_impurity_decrease' : uniform(0.0001, 0.001),
         'max_depth':randint(20, 50),
         'min_samples_split':randint(2, 25),
         'min_samples_leaf' : randint(1,25)}

In [44]:
from sklearn.model_selection import RandomizedSearchCV
gs = RandomizedSearchCV(DecisionTreeClassifier(random_state=42), params, n_iter=100, n_jobs=-1, random_state=42)
gs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002B662B79340>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002B6656325E0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002B662B79220>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002B66563D1F0>},
                   random_state=42)

In [45]:
print(gs.best_params_)

{'max_depth': 39, 'min_impurity_decrease': 0.00034102546602601173, 'min_samples_leaf': 7, 'min_samples_split': 13}


In [47]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8695428296438884


In [48]:
dt = gs.best_estimator_
print(dt.score(test_input, test_target))

0.86
