In [1]:
import tensorflow as tf

In [9]:
vocab = { "i" : 0, # 사용할 단어 사전 정의
         "need" : 1, 
         "some" : 2,
         "more" : 3,
         "coffee": 4,
         "cake" :5,
         "cat" :6, 
         "dog" : 7}

In [10]:
sentence = "i i i i need some more coffee coffee coffee"

In [11]:
_input = [vocab[w] for w in sentence.split()]

In [12]:
vocab_size = len(vocab)

In [13]:
import numpy as np

In [14]:
one_hot = tf.one_hot(_input, vocab_size)
print(one_hot.numpy())

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [15]:
distribution_size = 2
linear = tf.keras.layers.Dense(units=distribution_size, use_bias=False)
one_hot_linear = linear(one_hot)

In [16]:
print("Linear Weight")
print(linear.weights[0].numpy())

Linear Weight
[[ 0.47080028 -0.5064384 ]
 [-0.74999315 -0.07400519]
 [-0.19375849  0.29121208]
 [-0.38214952 -0.08357912]
 [ 0.6013448  -0.352039  ]
 [-0.50431234  0.18551874]
 [ 0.4121952  -0.64771277]
 [-0.15073991  0.24589467]]


In [17]:
print("one_hot Linear Result")
print(one_hot_linear.numpy())

one_hot Linear Result
[[ 0.47080028 -0.5064384 ]
 [ 0.47080028 -0.5064384 ]
 [ 0.47080028 -0.5064384 ]
 [ 0.47080028 -0.5064384 ]
 [-0.74999315 -0.07400519]
 [-0.19375849  0.29121208]
 [-0.38214952 -0.08357912]
 [ 0.6013448  -0.352039  ]
 [ 0.6013448  -0.352039  ]
 [ 0.6013448  -0.352039  ]]


In [18]:
words = tf.constant([[3, 57, 35]]) # 3번 단어 / 57번 단어 / 35번 단어로 이루어진 한 문장

In [19]:
print("Embedding을 진행할 문장:", words.shape)
embedding_layer = tf.keras.layers.Embedding(input_dim=64, output_dim=100)
# 총 64개의 단어를 포함한 Embedding 레이어 선언(input_dim은 vocab size)
# 각 단어를 100차원으로 분산 표현

Embedding을 진행할 문장: (1, 3)


In [20]:
print("Embedding된 문장:", embedding_layer(words).shape)
print("Embedding layer의 Weight 형태:", embedding_layer.weights[0].shape)


Embedding된 문장: (1, 3, 100)
Embedding layer의 Weight 형태: (64, 100)


In [21]:
raw_inputs =["나는 학생입니다.",
             "나는 좋은 선생님 입니다.",
             "당신은 매우 좋은 선생님 입니다."]
raw_labels=[1,0,0]

In [22]:
words = []
for s in raw_inputs : 
  words.extend(s.split())
print(words)

['나는', '학생입니다.', '나는', '좋은', '선생님', '입니다.', '당신은', '매우', '좋은', '선생님', '입니다.']


In [23]:
# 중복 단어 제거
words = list(dict.fromkeys(words))
print(words)

['나는', '학생입니다.', '좋은', '선생님', '입니다.', '당신은', '매우']


In [24]:
word_to_id = {"<PAD>" : 0 , "<UNK" : 1}

for w in words : 
  word_to_id[w] = len(word_to_id) # 단어를 하나하니씩 추가
  print(word_to_id)

{'<PAD>': 0, '<UNK': 1, '나는': 2}
{'<PAD>': 0, '<UNK': 1, '나는': 2, '학생입니다.': 3}
{'<PAD>': 0, '<UNK': 1, '나는': 2, '학생입니다.': 3, '좋은': 4}
{'<PAD>': 0, '<UNK': 1, '나는': 2, '학생입니다.': 3, '좋은': 4, '선생님': 5}
{'<PAD>': 0, '<UNK': 1, '나는': 2, '학생입니다.': 3, '좋은': 4, '선생님': 5, '입니다.': 6}
{'<PAD>': 0, '<UNK': 1, '나는': 2, '학생입니다.': 3, '좋은': 4, '선생님': 5, '입니다.': 6, '당신은': 7}
{'<PAD>': 0, '<UNK': 1, '나는': 2, '학생입니다.': 3, '좋은': 4, '선생님': 5, '입니다.': 6, '당신은': 7, '매우': 8}


In [25]:
word_to_id.items() # key와 values 값을 한꺼번에 출력

dict_items([('<PAD>', 0), ('<UNK', 1), ('나는', 2), ('학생입니다.', 3), ('좋은', 4), ('선생님', 5), ('입니다.', 6), ('당신은', 7), ('매우', 8)])

In [27]:
id_to_words = {i : w  for w, i in word_to_id.items()}
print(id_to_words)

{0: '<PAD>', 1: '<UNK', 2: '나는', 3: '학생입니다.', 4: '좋은', 5: '선생님', 6: '입니다.', 7: '당신은', 8: '매우'}


In [29]:
train_inputs = [] # 문장마다 시퀀스 변환하는 과정


for s in raw_inputs : 
  row = [word_to_id[w] for w in s.split()]

  # padding
  row += [0] * (5-len(row))
  train_inputs.append(row)

train_inputs = np.array(train_inputs)
print(train_inputs)

[[2 3 0 0 0]
 [2 4 5 6 0]
 [7 8 4 5 6]]


In [38]:
onehot_matrix = np.eye(len(word_to_id))
print(onehot_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [39]:
train_onehot = onehot_matrix[train_inputs]
print(train_onehot)

[[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]]]


In [40]:
train_onehot.shape

(3, 5, 9)

In [41]:
print(np.argmax(train_onehot, axis = -1))

[[2 3 0 0 0]
 [2 4 5 6 0]
 [7 8 4 5 6]]


In [45]:
x = np.argmax(train_onehot, axis = -1)
print(x)

[[2 3 0 0 0]
 [2 4 5 6 0]
 [7 8 4 5 6]]


In [43]:
import tensorflow.keras.layers as L

In [44]:
x_len = train_onehot.shape
print(x_len)

(3, 5, 9)


In [46]:
inp = tf.convert_to_tensor(x, dtype=tf.int32) # 정수 시퀀스
inp_len = tf.convert_to_tensor(x_len, dtype=tf.int32)

In [47]:
print(inp)
print(inp_len)

tf.Tensor(
[[2 3 0 0 0]
 [2 4 5 6 0]
 [7 8 4 5 6]], shape=(3, 5), dtype=int32)
tf.Tensor([3 5 9], shape=(3,), dtype=int32)


In [48]:
vocab_size = 1000
dim = 10
embed = L.Embedding(vocab_size, dim)

In [49]:
a = embed(inp)
print(a) # dim을 10으로 했기때문에 10차원으로 인식

tf.Tensor(
[[[-0.02447764 -0.01618337 -0.03300678 -0.04104597 -0.04125186
    0.04778821  0.02826991  0.04590381 -0.01875266  0.01135687]
  [ 0.01081587 -0.01189706  0.03582431  0.0363595  -0.01289396
   -0.00258211 -0.0249618   0.00876231 -0.0246371   0.03209183]
  [ 0.02016392 -0.04969443  0.03690008  0.02032795 -0.0458988
   -0.01893876 -0.01362979  0.01636875 -0.01790242 -0.02509079]
  [ 0.02016392 -0.04969443  0.03690008  0.02032795 -0.0458988
   -0.01893876 -0.01362979  0.01636875 -0.01790242 -0.02509079]
  [ 0.02016392 -0.04969443  0.03690008  0.02032795 -0.0458988
   -0.01893876 -0.01362979  0.01636875 -0.01790242 -0.02509079]]

 [[-0.02447764 -0.01618337 -0.03300678 -0.04104597 -0.04125186
    0.04778821  0.02826991  0.04590381 -0.01875266  0.01135687]
  [-0.01819559  0.04678586  0.00602917 -0.03069335  0.04505198
   -0.03727168  0.04006776 -0.00045945  0.04566682  0.00360245]
  [-0.04132884  0.00983325  0.00435482  0.00071216  0.03836671
   -0.04248431  0.02234424 -0.01816884

In [50]:
a.shape

TensorShape([3, 5, 10])

In [ ]:
emded layer를 쓰게 되면 차원을 마음대로 할 수 가 있음