In [1]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence, Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.models import Sequential        
from tensorflow.keras.preprocessing.sequence import pad_sequences

text = '해보지 않으면 해낼 수 없다'

result = text_to_word_sequence(text)
print("\n 원문 :\n", text)
print("\n 토큰화 :\n", result)


 원문 :
 해보지 않으면 해낼 수 없다

 토큰화 :
 ['해보지', '않으면', '해낼', '수', '없다']


In [2]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

In [3]:
# 토큰화 함수 지정 후 단어의 빈도수를 계산진행 
token = Tokenizer()
token.fit_on_texts(docs)
print("\n 단어 카운트 :\n", token.word_counts)


 단어 카운트 :
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [4]:
print("\n 문장 카운트 :\n", token.document_count)


 문장 카운트 :
 3


In [5]:
print("각 단어가 몇 개의 문장에 포함되어 있는가:", token.word_docs)

각 단어가 몇 개의 문장에 포함되어 있는가: defaultdict(<class 'int'>, {'먼저': 1, '각': 1, '단어를': 1, '나누어': 1, '토큰화합니다': 1, '텍스트의': 2, '토큰화해야': 1, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '사용할': 1, '수': 1, '토큰화한': 1, '결과는': 1, '있습니다': 1})


In [6]:
display("각 단어에 매겨진 인덱스 값: ", token.word_index)

'각 단어에 매겨진 인덱스 값: '

{'텍스트의': 1,
 '딥러닝에서': 2,
 '먼저': 3,
 '각': 4,
 '단어를': 5,
 '나누어': 6,
 '토큰화합니다': 7,
 '단어로': 8,
 '토큰화해야': 9,
 '인식됩니다': 10,
 '토큰화한': 11,
 '결과는': 12,
 '사용할': 13,
 '수': 14,
 '있습니다': 15}

In [7]:
# 단어의 원-핫 인코딩 _ 단어를 모두 0으로 바꾸고 원하는 단어만 1로 바꾸어 줌
text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [8]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [9]:
# 위 text를 벡터화 진행 (자세한건 책 참고 247p)
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [10]:
#[[[0. 1. 0. 0. 0. 0. 0.] 오랫동안
#  [0. 0. 1. 0. 0. 0. 0.] 꿈꾸는
#  [0. 0. 0. 1. 0. 0. 0.] 이는
#  [0. 0. 0. 0. 1. 0. 0.] 그
#  [0. 0. 0. 0. 0. 1. 0.] 꿈을
#  [0. 0. 0. 0. 0. 0. 1.]]] 닮아간다

In [11]:
# 단어 임배딩(word embedding)


model = Sequential()
# 입력될 총 단어수, 출력되는 벡터 크기
model.add(Embedding(16,4))

In [28]:
from numpy import array
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다",
        "한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

classes = array([1,1,1,1,1,0,0,0,0,0])

In [29]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [30]:
x = token.texts_to_sequences(docs)
print("리뷰텍스트의 토큰화 결과 :", x)

리뷰텍스트의 토큰화 결과 : [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [31]:
padded_x = pad_sequences(x, 4)  
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [32]:
word_size = len(token.word_index) + 1

In [33]:
# 임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) +1

# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 4, 8)              168       
                                                                 
 flatten_4 (Flatten)         (None, 32)                0         
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 691ms/step - loss: 0.7053 - accuracy: 0.3000
Epoch 2/20
1/1 [==============================] - 0s 3ms/step - loss: 0.7027 - accuracy: 0.3000
Epoch 3/20
1/1 [==============================] - 0s 5ms/step - loss: 0.7001 - accuracy: 0.4000
Epoch 4/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6975 - accuracy: 0.4000
Epoch 5/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6950 - accuracy: 0.4000
Epoch 6/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6924 - accuracy: 0.4000
Epoch 7/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6899 - accuracy: 0.4000
Epoch 8/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6874 - accuracy: 0.4000
Epoch 9/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6849 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6823 - accuracy: 0.8000
Epoch 11/20
1/1 [====================