In [3]:
# numpy : 배열을 처맇기 쉽게 제공하는 모듈
import numpy as np

In [4]:
list_a = list(range(15))
print(type(list_a), list_a)

<class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [5]:
arr = np.arange(15) # np.arange(start, stop, step)
print(type(arr), arr)

<class 'numpy.ndarray'> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
# 차원변경(array, reshape(행, 열))
arr = arr.reshape(3, 5)
print(arr.ndim) #차원출력
print(arr.shape) # 배열의 형태 3, 5
print(arr.size) # 배열의 전체 데이터개수
print(arr.dtype.name, arr.dtype.itemsize) # 데이터 타입의 이름, 저장 사이즈
print(arr)             # arr은 인덱스가 없을 뿐, 그래서 판다스를 이용해서 
                      # 칼럼과 인덱스를 설정해줘야함
arr.reshape(arr.size) # 평탄화

2
(3, 5)
15
int32 4
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
import pandas as pd
df = pd.DataFrame(arr)
print(df)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14


In [15]:
# 리스트를 array로 변경
arr_list = np.array(list_a)
print(arr_list)


print()
two_list =  np.array( [[1,2,3], [4,5,6]])
print(two_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[[1 2 3]
 [4 5 6]]


In [16]:
# 각 array의 차원, 배열 형식, 전체 사이즈, 데잍타입 출력
print(arr_list.ndim, arr_list.shape, arr_list.size, arr_list.dtype)
print(two_list.ndim, two_list.shape, two_list.size, two_list.dtype)

1 (15,) 15 int32
2 (2, 3) 6 int32


In [22]:
# array 생성
a = np.empty((3, 4))  # 메모리의 공간만 할당, 값은 초기화 시키지 않음
print(a)

# 초기 값을 0으로 부여하면서 배열 생성
a = np.zeros((2, 3))
print(a)

[[1. 0. 3. 0.]
 [3. 0. 3. 0.]
 [3. 0. 3. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# 초기 값을 0으로 부여하면서 배열 생성 => 기본적으로는 float
a = np.zeros((2, 3), dtype= 'i') # 데이터타입을 int 로.. / 소수점 없애줌
print(a)

[[0 0 0]
 [0 0 0]]


In [24]:
a = np.zeros((2, 3), dtype= 'U4') # U가 들어가면 데이터타입임
print(a)

[['' '' '']
 ['' '' '']]


In [25]:
a = np.zeros((2, 3), dtype= 'f') # 데이터타입을 float으로
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
a = np.zeros((2, 3), dtype= 'i8') # 데이터타입을 float으로
print(a, a.dtype.itemsize)

[[0 0 0]
 [0 0 0]] 8


In [28]:
# 데이터 초기 값을 1로 주면서 배열 생성
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b = np.zeros_like

In [29]:
# array 연산
x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])
x2 = np.array([[1.0, 2.0],[ 3.0, 4.0]]) 
y2 = np.array([[5.0,10.0],[15.0,20.0]]) 
z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

In [30]:
# array basic 연산
print(x1 + y1)
print(x2 * y2)

[ 6. 12. 18.]
[[ 5. 20.]
 [45. 80.]]


In [33]:
# array broadcast 연산
print(z1 + z2)
print(x1 ** 2)
print(x1 >= 2) # x1이 2보다 높은 값만 출력

[[ 4.  3.]
 [ 9.  8.]
 [14. 13.]]
[1. 4. 9.]
[False  True  True]


In [36]:
# shape
# x2 = np.array([[1.0, 2.0], [3.0, 4.0]])
x2.reshape(x2.size)
x2.flatten # 1차원으로 평탄화 
print(x2.flatten())

x2.flatten().reshape(2,2)

[1. 2. 3. 4.]


array([[1., 2.],
       [3., 4.]])

In [37]:
# indexing, slicing, iterating
a = np.arange(10) ** 2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [38]:
# 2번쨰 자료 출력
print(a[2])
# 2번째에서 4번쨰까지만 출력
print(a[ 2 :5]) # start : stop 에서 stop 포함 x

4
[ 4  9 16]


In [39]:
# 처음부터 끝까지 2칸씩 증가시키면서 출력
print(a[ : : 2])

[ 0  4 16 36 64]


In [40]:
a[0 : 6 : 2] = -a[0 : 6: 2]
print(a)

[  0   1  -4   9 -16  25  36  49  64  81]


In [41]:
# 뒤에서 부터 출력
print(a[ : : -1 ])

[ 81  64  49  36  25 -16   9  -4   1   0]


In [43]:
# for 를 사용하여 값을 출력
for i in a :
    print(i, end= ' ' ) # 출력하고 넘어강

0 1 -4 9 -16 25 36 49 64 81 

In [44]:
# 배열을 검색
a = np.arange(1, 21).reshape(4,5) # np 배열을 4행 5열로 만들겠따
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [45]:
# 배열의 각 원소 검색 : array([행, 열])
print(a[1,1]) # 1행 1열

7


In [48]:
print(a[1, 1]) # 1행 1열의 수
print(a[0:2, 1]) # 0행, 1행의 1열만 검색
print(a[-1 , -1]) # 마지막 행과 마지막 열 검색
print(a[1, ]) # 1행의 모든 열의 자료검색


7
[2 7]
20
[ 6  7  8  9 10]


In [52]:
# np.ndarray(shape, buffer=)
a = np.ndarray((3,2), buffer=np.arange(6), dtype=int)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [53]:
a = np.array([[0.1, 0.8, 0.2, 0.4],[0.3, 0.2, 0.5, 0.6], [0.9, 0.5, 0.3, 0.5]])
print(np.argmax(a, axis=0)) # axis = 0 > x축으로 감
print(np.argmax(a, axis=1)) # axis = 1 > y축으로 감

[2 0 1 1]
[1 3 0]


In [54]:
print(a)

[[0.1 0.8 0.2 0.4]
 [0.3 0.2 0.5 0.6]
 [0.9 0.5 0.3 0.5]]


In [55]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
print(len(x))
print(x.min(), x.max(), x.mean(), x.std(), x.var())
print(np.median(x), np.percentile(x, 25), np.percentile(x, 100))

26
-24 23 4.8076923076923075 10.734628476137871 115.23224852071006
5.0 0.0 23.0


In [58]:
# 난수 생성
# rand : 0 부터 1사이의 균일분포(정규분포=그래프를 그렸을때 그래프가 원만하게 올라갔다가 내려오는 그래프)로 난수 생성
# randn : 기댓값이 0이고 표준편차가 1인 가우시간 표준 정규 분포를 따르는 난수 생성
# randint : 균일 분포의 정수 난수
np.random.rand(10)
np.random.randn(10)
np.random.randint(10, size=10)      # 10에서까지의 숫자 중에 차례대로 10개로

array([3, 7, 1, 9, 4, 9, 6, 1, 9, 5])

In [59]:
np.random.randint(10, size=(2,5))

array([[0, 4, 1, 5, 1],
       [5, 4, 3, 2, 2]])

In [62]:
np.random.seed(10) # seed를 넣는 난수초기화, 순간 동일한 난수만 나옴
print(np.random.randint(10, 20, size=(2,5)))

[[19 14 10 11 19]
 [10 11 18 19 10]]


In [63]:
x = np.arange(10) # 0~9까지의 정수 발생, 1차원 배열
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [66]:
# 자료의 위치를 바꿈 -> 계속 위치가 바뀜
np.random.shuffle(x)
print(x)

[0 1 5 8 9 4 7 6 3 2]


In [69]:
# 샘플링 함수 : choice 함수
# np.random.choice(data 또는 숫자(정수), size=None, replace=True, p=None) -> None은 안써도됌
np.random.choice(5, size=5, replace=False) # data= np.arange(5), size=5 
# = shuffle 과 동일

array([3, 4, 2, 1, 0])

In [70]:
np.random.choice(5, 3, replace=False) # 5개중 3개만 선택

array([2, 4, 1])

In [71]:
np.random.choice(5, 10) # 반복 허용 replace=True 가 기본값

array([3, 4, 1, 4, 2, 0, 0, 4, 4, 0])

In [80]:
np.random.choice(5, 10, p= [0.1, 0, 0.2, 0.5, 0.2])
# 

array([3, 3, 0, 3, 3, 2, 3, 3, 2, 0])

In [81]:
# 1 부터 20까지의 수를 가진 array 생성
# 배열에서 3의 배수를 검색
# 4를 나누면 1이남는 수 ㄱㅁ색
# 3을 나누면 나누어지고 4로 나누면 1이 남는 수 검색
x = np.arrange(1, 21)
print(x[x%3 ==0])
print(x[x%4==1])
print(x[x%3==0])& (x %4 ==1))
            
print(x[])

SyntaxError: unmatched ')' (3831310007.py, line 8)