In [1]:
# 판다스의 자료구조 : 시리즈, 데이터프레임
import pandas as pd

In [4]:
# 시리즈 생성  Series(딕셔너리 또는 리스트, index=[ ])
sr = pd.Series({'a':1, 'b':2, 'c':3})
print(sr)

print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
# 시리즈의 인덱스, 값
print(sr.index)
print(sr.values)

Index(['a', 'b', 'c'], dtype='object')
[1 2 3]


In [10]:
# 시리즈를 접근하는 방법 : sr[index], sr[숫자인덱스]
print(sr['a'], sr[0])
print()
print(sr['a':'c'])  # 인덱스명으로 접근시 end도 포함
print()
print(sr[0:2])   # 숫자 인덱스로 접근하면 end는 미포함

1 1

a    1
b    2
c    3
dtype: int64

a    1
b    2
dtype: int64


In [11]:
# 리스트 또는 튜플을 시리즈로 만들면서 인덱스명 부여
list_data = [ '영인', '2000-06-30', '남', True]
sr1 = pd.Series(list_data, index=['이름', '생년월일','성별', '학생여부'])
sr1

이름              영인
생년월일    2000-06-30
성별               남
학생여부          True
dtype: object

In [13]:
sr1[ ['이름', '생년월일'] ]

이름              영인
생년월일    2000-06-30
dtype: object

In [22]:
print(sr1.dtype)  # 시리즈에 저장된 데이터 타입 숫자 ->int64 문자 -> object
print(type(sr1['이름']))

object
<class 'str'>


In [23]:
print(sr.dtype)  # 시리즈에 저장된 데이터 타입 숫자 ->int64 문자 -> object
print(type(sr['a']))

int64
<class 'numpy.int64'>


In [25]:
#  데이터프레임 : 시리즈가 여러개 묶여서 됨
# 딕셔너리로 데이터프레임 생성 -> 키가 컬럼으로 됨
dict_data = {'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]}
df = pd.DataFrame(dict_data)
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [29]:
print(type(df))
print(df.dtypes)  #  각 컬럼의 데이터 타입
print(df.index)   # 데이터프레임의 인덱스 출력
print(df.values)  # 각 인덱스의 값 : 2차원 리스트

<class 'pandas.core.frame.DataFrame'>
a    int64
b    int64
c    int64
dtype: object
RangeIndex(start=0, stop=3, step=1)
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
#  2차원 리스트로 인덱스명과 컬럼명을 부여하면서 데이터프레임 생성
data = [[15,'남', '덕영중'], [17,'여', '수리중']]
df = pd.DataFrame(data, index=['준서', '예은'],
                 columns=['나이','성별','학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [36]:
print(df.dtypes)
print()
print(df.index)
print()
print(df.columns)

# 인덱스명을 변경 : 객체.index = [ 인덱스명, .. ], 기존의정보 수정
# 컬럼명을 변경 : 객체.columns = [ 컬럼명 , .. ], 기존의 정보 수정
# 준서, 예은 -> 학생1, 학생2
df.index = ['학생1','학생2']
print(df)
print()
df.columns = [ '연령','남녀', '소속']
print(df)

나이     int64
성별    object
학교    object
dtype: object

Index(['학생1', '학생2'], dtype='object')

Index(['나이', '성별', '학교'], dtype='object')
     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중


In [38]:
df

연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [40]:
# 인덱스명과 컬럼명을 일부만 수정하고자 할 경우 : 
# object.rename(index={old:new, ...}, inplace=True) -> 기존의 정보 변경
# object.rename(columns={old:new, ...})
# 남녀를 성별로, 학생1을 준서로 수정
df.rename(index={'학생1':'준서'}, columns={'남녀':'성별'}, inplace=True)
df_copy = df.rename(index={'학생1':'준서'}, columns={'남녀':'성별'})

In [41]:
df

연령 성별   소속
준서   15  남  덕영중
학생2  17  여  수리중

In [42]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

In [43]:
# 서준, 우현, 인아 로 인덱스 설정 하면서 exam_data를 이용하여 df 을 생성 
df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
print(df)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90


In [50]:
# 행의 자료를 삭제 : 객체.drop(행인덱스 또는 배열, axis=0)
# 열(컬럼)의 자료를 삭제 : 객체.drop(열인덱스 또는 배열, axis=1)
# 서준와 우현의 자료를 삭제  
print(df.drop(['서준','우현'], axis=0))
print()
print(df.drop('수학', axis=1))

    수학  영어   음악  체육
인아  70  95  100  90

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90


In [56]:
exam_data = [ [ 90, 80, 70], [ 98, 89, 95],
             [ 85, 95, 100],  [ 100, 90, 90]]
# exam_data 를 데이터 프레임으로 생성 
df = pd.DataFrame(exam_data)
print(df)
print()
# 인덱스명 추가 서준,준서,인아,연아
df.index = ['서준','준서','인아','연아']
print(df)
# 컬럼명 추가 : 국어, 영어, 수학,
df.columns = ['국어', '영어', '수학']
print(df)
# 수학 컬럼을 체육 수정해서 기존 자료에 반영
df.rename(columns={'수학':'체육'}, inplace=True)
print()
print(df)
print()
# 영어 컬럼 자료 삭제 : 기존 자료에 반영하지 않음 , 결과만 확인
print(df.drop('영어',axis=1))
print()
# 서준자료 삭제 : 기존 자료에 반영하지 않음, 결과만 확인
print(df.drop('서준',axis=0))

     0   1    2
0   90  80   70
1   98  89   95
2   85  95  100
3  100  90   90

      0   1    2
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90
     국어  영어   수학
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90

     국어  영어   체육
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90

     국어   체육
서준   90   70
준서   98   95
인아   85  100
연아  100   90

     국어  영어   체육
준서   98  89   95
인아   85  95  100
연아  100  90   90


In [59]:
df_copy = df
df_copy.drop('연아',axis=0, inplace=True)
df_copy
             

국어  영어   체육
서준  90  80   70
준서  98  89   95
인아  85  95  100

In [61]:
exam_data = [ [ 90, 80, 70], [ 98, 89, 95],
             [ 85, 95, 100],  [ 100, 90, 90]]
# exam_data 를 데이터 프레임으로 생성 
df = pd.DataFrame(exam_data)
print(df)
print()
# 인덱스명 추가 서준,준서,인아,연아
df.index = ['서준','준서','인아','연아']
print(df)
# 컬럼명 추가 : 국어, 영어, 수학,
df.columns = ['국어', '영어', '수학']

     0   1    2
0   90  80   70
1   98  89   95
2   85  95  100
3  100  90   90

      0   1    2
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90


In [64]:
df_copy_1 = df.copy()
df_copy_1.drop('연아',axis=0, inplace=True)
print(df_copy_1)
print()
print(df)

    국어  영어   수학
서준  90  80   70
준서  98  89   95
인아  85  95  100

     국어  영어   수학
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90
