In [1]:
# 판다스의 자료구조 : 시리즈, 데이터프레임
import pandas as pd

In [4]:
# 시리즈 생성 Series(딕셔너리 또는 리스트, indax=[ ]) 값이 여러개다 list
sr = pd.Series({'a':1, 'b':2, 'c':3}) # 앞에는 인덱스
print(sr)

print(type(sr)) # 판다스의 시리즈 타입이다

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
# 시리즈의 인덱스, 값
print(sr.index)
print(sr.values)

Index(['a', 'b', 'c'], dtype='object')
[1 2 3]


In [9]:
# 시리즈를 접근하는 방법 : sr[index], sr[숫자인덱스]
print(sr['a'], sr[0])
print()
print(sr['a':'c'])  # 인덱스명으로 접근시 end도 포함_시리즈 생성한게 a~c인데 3개 다 보여짐
print()
print(sr[0:2]) # 숫자 인덱스로 접근하면 end는 미포함

1 1

a    1
b    2
c    3
dtype: int64

a    1
b    2
dtype: int64


In [10]:
# 리스트 또는 튜플을 시리즈로 만들면서 인덱스명 부여
list_data = ['영인', '2000-06-30', '남', True]
srl = pd.Series(list_data, index=['이름', '생년월일', '성별', '학생여부'])
# 판다스 시리즈의 list
print(srl)

이름              영인
생년월일    2000-06-30
성별               남
학생여부          True
dtype: object


In [11]:
srl[['이름', '생년월일']] # list 내에서 추출하고싶을때 [[]]

이름              영인
생년월일    2000-06-30
dtype: object

In [18]:
print(sr.dtype) # 시리즈에 저장된 데이터 타입 숫자 -> int64 문자출력 -> object
print(type(sr['a']))

int64
<class 'numpy.int64'>


In [23]:
# 데이터 프레임 : 시리즈가 여러개 묶여서 됨
# 딕셔너리로 데이터프레임 생성 -> 키가 칼럼으로 됨
dict_data = {'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]}
df = pd.DataFrame(dict_data)
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [25]:
print(type(df))
print()
print(df.dtypes) # 각 칼럼의 데이터 타입
print()
print(df.index) # 데이터프레임의 인덱스 출력
print()
print(df.values) # 각 인덱스의 값 : 2차원 리스트

<class 'pandas.core.frame.DataFrame'>

a    int64
b    int64
c    int64
dtype: object

RangeIndex(start=0, stop=3, step=1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
# 2차원 리스트로 인덱스 명과 칼럼명을 부여하면서 데이터프레임 생성
data = [[15, '남', '덕영중'], ['17', '여', '수리중']]
df = pd.DataFrame(data, index=['준서', '예은'],
                  columns=['나이', '성별', '학교'])
print(df)

                               

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중


In [28]:
print(df.dtypes)
print()
print(df.index)
print()
print(df.columns)

나이    object
성별    object
학교    object
dtype: object

Index(['준서', '예은'], dtype='object')

Index(['나이', '성별', '학교'], dtype='object')


In [30]:
# 인덱스명을 변경 : 객체.index = [인덱스명, ..] -> 객체같은느낌
# 컬럼명을 변경 : 객채.colums = [컬럼명, ..] ->제목같은느낌
# 준서, 예은 -> 학생1, 학생2
df.index = ['학생1', '학생2']
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중


In [31]:
df.columns = ['연령', '남녀', '소속']
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중


In [34]:
# 인덱스명과 컬럼명을 일부만 수정하고자 할 경우:
# object.rename(index=(old:new, ...)), inplace=True -> 기본의 정보 변경
# object.rename(colums= old:new, ...))
# 남녀를 성별로, 학생1을 준서로 수정
df.rename(index={'학생1': '준서'}, columns = {'남녀':'성별'}, inplace=True)
df_copy = df.rename(index={'학생1': '준서'}, columns = {'남녀':'성별'})

In [35]:
df

연령 성별   소속
준서   15  남  덕영중
학생2  17  여  수리중

In [36]:
exam_data = {'수학' : [90,80,70], '영어' :[98,89,95],
            '음악':[85,95,100], '체육':[100,90,90]}

In [37]:
# 서준 우현 인아로 인덱스 설정하면서 exam_data를 이용하여 df를 생성
df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
print(df)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90


In [42]:
# 행의 자료를 삭제 : 객체.drop(행인덱스 또는 배열, axis=0)
# 열(컬럼)의 자료를 삭제 : 객체.drop(열인덱스 또는 배열, axis=1)
# 서준이와 우현의 자료를 삭제
print(df.drop(['서준','우현'], axis =0))
print()
print(df.drop('수학', axis=1))

    수학  영어   음악  체육
인아  70  95  100  90

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90


In [70]:
exam_data = [[90,80,70], [98,89,95],
            [85,95,100], [100,90,90]]
# exam_data를 데이터프레임으로 생성
df = pd.DataFrame(exam_data)
print(df)
# 인덱스명 추가 서준, 준서, 인아, 연아
df.index = ['서준', '준서', '인아', '연아']
print(df)
# 컬럼명 추가 : 국어, 영어, 수학, 음악
df.columns = ['국어', '영어', '수학', '음악']
print(df)
# 음악 칼럼명을 체육으로 수정해서 기존 자료에 반영
df.rename(columns=['국어', '영어', '수학', '체육'])
# 영어 컬럼 자료 삭제 : 기존 자료에 반영하지 않음, 결과만 확인
# 서준자료 삭제 : 기존 자료에 반영하지 않음, 결과만 확인

     0   1    2
0   90  80   70
1   98  89   95
2   85  95  100
3  100  90   90
      0   1    2
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90


ValueError: Length mismatch: Expected axis has 3 elements, new values have 4 elements

In [71]:
exam_data = [ [ 90, 80, 70], [ 98, 89, 95],
             [ 85, 95, 100],  [ 100, 90, 90]]         ###강사님
# exam_data 를 데이터 프레임으로 생성 
df = pd.DataFrame(exam_data)
print(df)
print()
# 인덱스명 추가 서준,준서,인아,연아
df.index = ['서준','준서','인아','연아']
print(df)
# 컬럼명 추가 : 국어, 영어, 수학,
df.columns = ['국어', '영어', '수학']
print(df)
# 수학 컬럼을 체육 수정해서 기존 자료에 반영
df.rename(columns={'수학':'체육'}, inplace=True)
print()
print(df)
print()
# 영어 컬럼 자료 삭제 : 기존 자료에 반영하지 않음 , 결과만 확인
print(df.drop('영어',axis=1))
print()
# 서준자료 삭제 : 기존 자료에 반영하지 않음, 결과만 확인
print(df.drop('서준',axis=0))

     0   1    2
0   90  80   70
1   98  89   95
2   85  95  100
3  100  90   90

      0   1    2
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90
     국어  영어   수학
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90

     국어  영어   체육
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90

     국어   체육
서준   90   70
준서   98   95
인아   85  100
연아  100   90

     국어  영어   체육
준서   98  89   95
인아   85  95  100
연아  100  90   90


In [72]:
df_copy = df
df_copy.drop('연아',axis=0, inplace=True)
df_copy
             

국어  영어   체육
서준  90  80   70
준서  98  89   95
인아  85  95  100

In [73]:
exam_data = [ [ 90, 80, 70], [ 98, 89, 95],
             [ 85, 95, 100],  [ 100, 90, 90]]
# exam_data 를 데이터 프레임으로 생성 
df = pd.DataFrame(exam_data)
print(df)
print()
# 인덱스명 추가 서준,준서,인아,연아
df.index = ['서준','준서','인아','연아']
print(df)
# 컬럼명 추가 : 국어, 영어, 수학,
df.columns = ['국어', '영어', '수학']

     0   1    2
0   90  80   70
1   98  89   95
2   85  95  100
3  100  90   90

      0   1    2
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90


In [74]:
df_copy_1 = df.copy()
df_copy_1.drop('연아',axis=0, inplace=True)
print(df_copy_1)
print()
print(df)

    국어  영어   수학
서준  90  80   70
준서  98  89   95
인아  85  95  100

     국어  영어   수학
서준   90  80   70
준서   98  89   95
인아   85  95  100
연아  100  90   90


In [81]:
# 행을 선택 : object.loc[인덱스명] < 인덱스명으로 선택
#             object.iloc[정수인덱스] < 정수형인덱스로 선택
print(df.loc['서준'])
print()
print(df.iloc[0])

# 범위로 선택: 서준과 우현의 자료검색
# 인덱스 명으로 검색 object.loc [ start : end] -> end 포함
# 정수 인덱스로 검색 object.iloc [start: end] -> end 미포함
print(df.loc['서준' : '우현']) # 서준과 우현 자료 출력
print()
print(df.iloc[0:2]) # 0행과 1행 출력, 2행은 포함 X

# 서준과 인아의 정보출력
print(df.loc[['서준', '인아']])
print(df.iloc[[0,2]])

국어    90
영어    80
수학    70
Name: 서준, dtype: int64

국어    90
영어    80
수학    70
Name: 서준, dtype: int64


KeyError: '우현'

In [82]:
# 열을 선택 : object(컬럼명] 또는 object : 칼럼명)
print(df.수학)
print()
print(df[['수학' : '체육']])

SyntaxError: invalid syntax (259331920.py, line 4)

In [83]:
# 원소 선택 : object.loc [ 행인덱스명, 컬럼 인덱스명]
#             objject.iloc[행의 정수인덱스, 칼럼정수인덱스]

# 인아의 수학과 체육 점수를 출력
df.loc['인아', ['수학', '체육']]
df.iloc[-1, [0, -1]]

# 서준부터 우현까지 수학에서 음악 점수를 출력
df.loc['서준':'우현', '수학':'음악']


KeyError: "['체육'] not in index"

In [84]:
# 열 추가 : object['새로운 컬럼명'] = 값
# '국어' 점수 추가 100
df['국어'] = 100
df

국어  영어   수학
서준  100  80   70
준서  100  89   95
인아  100  95  100
연아  100  90   90

In [86]:
# 행 추가 : object.loc[새로운 행 이름] = 값 또는 배열
df.loc['철수'] = [99, 80, 90] # 80만쓰면 통일은 그냥 한 점수
df

국어  영어   수학
서준  100  80   70
준서  100  89   95
인아  100  95  100
연아  100  90   90
철수   99  80   90

In [87]:
# 서준의 영어 점수를 100으로 수정
df.iloc[0,1] = 100 # 2번째까지 수정
df

국어   영어   수학
서준  100  100   70
준서  100   89   95
인아  100   95  100
연아  100   90   90
철수   99   80   90

In [89]:
# 서준의 수학 점수와 국어 점수를 77로 수정
df.loc['서준', ['수학', '국어']] = 77
print(df)
# 우현의 수학 점수와 국어 점수를 77 88 로 수정
df.loc['우현', ['수학', '국어']] = 77, 88
print(df)

     국어   영어   수학
서준   77  100   77
준서  100   89   95
인아  100   95  100
연아  100   90   90
철수   99   80   90
       국어     영어     수학
서준   77.0  100.0   77.0
준서  100.0   89.0   95.0
인아  100.0   95.0  100.0
연아  100.0   90.0   90.0
철수   99.0   80.0   90.0
우현   88.0    NaN   77.0


In [91]:
# 행과 열의 위치 변경 : object.transpose(), object.T
df_t = df.T
df_t.transpose()

국어     영어     수학
서준   77.0  100.0   77.0
준서  100.0   89.0   95.0
인아  100.0   95.0  100.0
연아  100.0   90.0   90.0
철수   99.0   80.0   90.0
우현   88.0    NaN   77.0

In [98]:
exam_data = {'이름 ' : ['서준','우현','인아'],
            '수학' : [90,80,70],
            '영어' : [100,80,90],
            '음악' : [100,90,100],
            '체육' : [90,80,70]}
df = pd.DataFrame(exam_data)
df

이름   수학   영어   음악  체육
0  서준  90  100  100  90
1  우현  80   80   90  80
2  인아  70   90  100  70

In [99]:
# 특정 칼럼을 인덱스로 설정 : object.set_index(컬럼명)
# 이름 컬럼을 index로 설정
df.set_index('이름', inplace=True)
df

KeyError: "None of ['이름'] are in the columns"

In [94]:
# 인덱스 초기화 : object.reset_index()
df.reset_index(inplace=True)
df

index 이름   수학   영어   음악  체육
0      0  서준  90  100  100  90
1      1  우현  80   80   90  80
2      2  인아  70   90  100  70

In [97]:
ndf = df.set_index('이름')
ndf

KeyError: "None of ['이름'] are in the columns"

In [100]:
# 인덱스를 재배열 : object.reindex(인덱스 리스트)
idx_list = ['서준', '철수', '우현', '인아', '나래']
ndf_1 = ndf.reindex(idx_list)
ndf_1

NameError: name 'ndf' is not defined

In [101]:
# 인덱스 기준으로 정렬 : object.sort_index()
ndf_1.sort_index()
ndf_1


NameError: name 'ndf_1' is not defined

In [103]:
# 컬럼 값을 기준으로 정렬 : object.sort_values(by=컬럼, ascending=False) 
ndf.sort_values(by='수학', ascending=False)
ndf.sort_values(by=['음악','수학'], ascending=False) # 여러개 할땐 괄호

NameError: name 'ndf' is not defined

In [ ]:
# df.set_index(), df.reset_index(), df.reindex(인덱스 리스트)
# df.sort_index, df.sort_values(by=[컬럼, ,,], ascending=False)

In [104]:
# part 산술연산
# 시리즈 연산
student1 = pd.Series({'국어' : 100, '영어':80, '수학':90})
print(student1)

국어    100
영어     80
수학     90
dtype: int64


In [105]:
# 각 점수를 100으로 나눈 값을 출력 할래
print(student1 /100)

국어    1.0
영어    0.8
수학    0.9
dtype: float64


In [106]:
# 각 점수에 100을 더할래
print(student1 + 100)

국어    200
영어    180
수학    190
dtype: int64


In [107]:
# 시리즈 vs 시리즈 연산 (+ - * / )
student2 = pd.Series({'국어' : 90, '영어':80, '수학':100})
student1 + student2

국어    190
영어    160
수학    190
dtype: int64

In [109]:
add = student1 + student2
sub = student1 - student2
mul = student1 * student2
div = student1 / student2

df = pd.DataFrame([add, sub, mul, div],
                 index=['+','-','*','/'])
df

국어      영어      수학
+   190.000000   160.0   190.0
-    10.000000     0.0   -10.0
*  9000.000000  6400.0  9000.0
/     1.111111     1.0     0.9

In [112]:
# 연산식에 Nan이 존재하면 연산의 결과는 Nan [위에랑 같음]
import numpy as np

stud1 = pd.Series({'국어' : np.nan, '수학':100, '영어':80})
stud2 = pd.Series({'국어' : 100, '수학':100})
df

국어      영어      수학
+   190.000000   160.0   190.0
-    10.000000     0.0   -10.0
*  9000.000000  6400.0  9000.0
/     1.111111     1.0     0.9

In [120]:
sns.get_dataset_names()  # 정보를 가져옴

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'taxis',
 'tips',
 'titanic']

In [115]:
# 데이터프레임 연ㅇ산
# 데이터 프레임 연산자(+ - * /) 숫자
# seaborn 에서ㅓ 제공하는 데이터셋을 로드
import seaborn as sns

# titanic 데이터 셋을 불러옴 : sns.load_dataset('titanic')
titanic = sns.load_dataset('titanic')
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [119]:
# titanic 에서 age와 fare 컬럼의 정보만 가져와서 df에 저장
#  df = titanic[['age', 'fare']] # 컬럼 정보 추출
df = titanic[['age', 'fare']]
df

age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [121]:
# 100번째 부터 200버ㅓㄴ째 까지의 'age'와 'fare' 컬럼만 추출
df = titanic.loc[ : , ['age', 'fare']]
df

age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [125]:
# df.head() : 처음부터 5개만, df.head(10), df.tail()
df.head(10)
# df.tail()

age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [126]:
add_df = df + 10
add_df.tail()

age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [127]:
(df + add_df).head()

age      fare
0  54.0   24.5000
1  86.0  152.5666
2  62.0   25.8500
3  80.0  116.2000
4  80.0   26.1000

In [135]:
df_mpg = sns.load_dataset('mpg')   #######과제 확인하쇼
df_mpg.info()
# mpg 데이터셋을 로드해서
# 1 mpg, weight 컬럼을 추출해서 데이터프레임으로 생성
print()
df = df_mpg[['mpg', 'weight']]
print(df)
# 2 각 원소에 100을 더한 값을 출력
print()
add_df = df + 100
print(df)
# 데이터프레임을 처음 10개의 정보만 출력
print()
add_df.tail(10)
print(df)
# 처음부터 100개의 행만 추출하여 mpg_sample 데이터 프레임생성

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

      mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ...     ...
393  27.0    2790
394  44.0    2130
395  32.0    2295
396  28.0    2625
397  31.0    2720

[398 rows x 2 columns]

      mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ... 